
--Query 1
SELECT customers.city, COUNT(*) AS order_count
FROM orders INNER JOIN customers ON orders.customer_id = customers.customer_id
GROUP BY city;
--Mistake explanation
--The orders table does not contain a city column. The query must join the customers table to access the customer's city.
--Business meaning
--Shows how many orders were placed from each city.

--Query 2
SELECT product_name, SUM(quantity * price) AS revenue
FROM orders
JOIN products ON orders.product_id = products.product_id
WHERE status = 'completed'
GROUP BY product_name;
--Mistake explanation
--A comma was missing after product_name. SQL requires commas to separate selected columns.
--Business meaning
--Shows the completed revenue generated by each product.


--Query 3
SELECT status, COUNT(*) AS order_count
FROM orders
GROUP BY status
ORDER BY order_count DESC;
--Mistake explanation
--A semicolon was placed after GROUP BY status, which ended the statement before ORDER BY. ORDER BY must be part of the same query.
--Business meaning
--Shows the number of orders for each status, sorted from highest to lowest.


--Query 4
SELECT order_id, quantity, price, quantity * price AS total_amount FROM orders
INNER JOIN products ON orders.product_id = products.product_id
--Mistake explanation
--The price column does not exist in the orders table. It must be retrieved from the products table by joining on product_id.
--Business meaning
--Calculates the total amount for every order.


--Query 5
SELECT category, SUM(quantity) AS total_quantity
FROM orders
INNER JOIN products ON orders.product_id = orders.product_id
WHERE status = 'completed'
GROUP BY category;
--Mistake explanation
--This compares the same column to itself, creating an incorrect join. It should join orders.product_id with products.product_id.
--Business meaning
--Shows the total quantity sold for each product category using only completed orders.


--Query 6
SELECT SUM(orders.quantity * products.price) AS total_revenue
FROM orders
JOIN products ON orders.product_id = products.product_id
WHERE status = 'completed';
--Mistake explanation
--The original query is valid. Using fully qualified column names (orders.quantity, products.price) simply makes the query clearer and avoids ambiguity and the sum is calculated for all products even for cancelled
--Business meaning
--Calculates the total revenue from all orders that are completed


--Query 7
SELECT customer_id, COUNT(*) AS order_count
FROM orders
GROUP BY customer_id
HAVING COUNT(*) > 1
--Mistake explanation
--HAVING was placed before GROUP BY. SQL requires GROUP BY first, followed by HAVING.
--Business meaning
--Shows customers who have placed more than one order.


--Query 8
SELECT orders.order_id, customers.customer_name
FROM orders
INNER JOIN customers ON  orders.customer_id = customers.customer_id
--Mistake explanation
--The JOIN was missing an ON condition. Without it, SQLite does not know how the two tables are related.
--Business meaning
--Displays each order together with the customer who placed it.

--Query 9
SELECT orders.customer_id, products.product_id, products.price
FROM orders
INNER JOIN products ON orders.product_id = products.product_id;
--Mistake explanation
--The original query selected price without qualifying the table. Using products.price makes it clear where the column comes from and avoids ambiguity.
--Business meaning
--Shows which customer ordered which product along with the product price.

--Query 10
SELECT *
FROM orders
WHERE status != 'completed';
--Mistake explanation
--The original query returned completed orders. If the requirement is to show orders that should not count as revenue, the filter must exclude completed orders using != 'completed'.
--Business meaning
--Lists all orders that are not completed, such as pending or cancelled orders, which should not be counted as revenue.